spring.cloud.consul.enabled=false
spring.cloud.consul.discovery.enabled=false
spring.cloud.consul.discovery.register=false

spring.datasource.url=jdbc:postgresql://localhost:5434/orderdb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=order_user
spring.datasource.password=order_pass
