spring.application.name=order-service
server.port=8083

spring.config.import=optional:configserver:http://localhost:8888

spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.service-name=${spring.application.name}
spring.cloud.consul.discovery.health-check-path=/actuator/health
spring.cloud.consul.discovery.prefer-ip-address=true
spring.cloud.consul.discovery.register=true
spring.cloud.consul.discovery.enabled=true

spring.datasource.url=jdbc:postgresql://localhost:5434/orderdb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=order_user
spring.datasource.password=order_pass

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

logging.level.com.example.order_service=DEBUG
logging.level.org.springframework.web=INFO
