spring.cloud.consul.enabled=false
spring.cloud.consul.discovery.enabled=false
spring.cloud.consul.discovery.register=false

spring.datasource.url=jdbc:postgresql://localhost:5434/orderdb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=order_user
spring.datasource.password=order_pass

# --- Performance dev : desactiver les logs SQL verbose --------------------------
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# --- Reduire le timeout de connexion au config-server --------------------------
spring.cloud.config.request-connect-timeout=1000
spring.cloud.config.request-read-timeout=1000
