# --- Profile: dev -------------------------------------------------------------
spring.cloud.consul.enabled=false
spring.cloud.consul.discovery.enabled=false
spring.cloud.consul.discovery.register=false

spring.datasource.url=jdbc:postgresql://localhost:5433/inventorydb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=inventory_user
spring.datasource.password=inventory_pass
